version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: repo
    volumes:
      - timescale-data:/var/lib/postgresql/data
    
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - cache:/data

volumes:
  timescale-data:
  cache:
    driver: local
    