export const eventData = [
    {
      id: 1,
      title: "India to win the 1st Test vs Bangladesh?",
      traders: 75612,
      icon: "🏏",
      status: "IND lead by 514 runs",
      yesOption: { text: "Yes", price: "₹9.7" },
      noOption: { text: "No", price: "₹0.3" },
    },
    {
      id: 2,
      title: "Bitcoin to be priced at 62974.01 USDT or more at 01:05 PM?",
      traders: 454,
      icon: "₿",
      status: "Bitcoin open price at 12:55 PM was 62974.01USDT.",
      yesOption: { text: "Yes", price: "₹8" },
      noOption: { text: "No", price: "₹2" },
    },
    {
      id: 3,
      title: "England to win the 2nd ODI vs Australia?",
      traders: 4543,
      icon: "🏏",
      status: "H2H last 5 ODI : ENG 0 , Australia 5, DRAW 0",
      yesOption: { text: "Yes", price: "₹4.1" },
      noOption: { text: "No", price: "₹5.9" },
    },
    {
      id: 4,
      title: "'Sourav Joshi - Bathroom Mein Lock Hogya' video to cross 3.06M views at 12:00 AM?",
      traders: 2696,
      icon: "🎥",
      status: "Current Views Rate is 21.197K ; Required Views Rate was 13.955K | Data as of 10:40 AM - 10:45 AM",
      yesOption: { text: "Yes", price: "₹4" },
      noOption: { text: "No", price: "₹6" },
    },
  ];